docker img structure modifed

diff --git a/container/Dockerfile b/container/Dockerfile
--- a/container/Dockerfile
+++ b/container/Dockerfile
@@ -1,38 +1,61 @@
-FROM python:3.7-slim-stretch
+FROM openjdk:11-jre-slim
 
 RUN apt-get update -y && apt-get install -y libzbar-dev bash gcc git libc-dev curl wget vim nano \
-    && apt-get install -y ranger caca-utils highlight atool w3m poppler-utils mediainfo \
     && apt-get install -y iputils-ping telnet openssh-client net-tools \
     man unzip vim-tiny bc openssh-server thrift-compiler netcat sudo \
     && apt-get install -y build-essential \
     && apt-get autoremove -y \
+    && rm -rf /var/lib/apt/lists/* \
     && apt-get clean
 
-# Install OpenJDK 8
-RUN mkdir -p /usr/share/man/man1mkdir -p /usr/share/man/man1 && \
-    apt-get update && \
-    apt-get install -y openjdk-8-jdk && \
-    rm -rf /var/lib/apt/lists/*
 
-ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
-ENV PATH=$PATH:$JAVA_HOME/bin
-RUN echo $JAVA_HOME
+RUN set -ex && \
+    sed -i 's/http:\/\/deb.\(.*\)/https:\/\/deb.\1/g' /etc/apt/sources.list && \
+    apt-get update && \
+    ln -s /lib /lib64 && \
+    apt-get install -y bash tini libc6 libpam-modules libnss3 procps && \
+    rm /bin/sh && \
+    ln -sv /bin/bash /bin/sh && \
+    echo "auth required pam_wheel.so use_uid" >> /etc/pam.d/su && \
+    chgrp root /etc/passwd && chmod ug+rw /etc/passwd && \
+    rm -rf /var/cache/apt/*
+
+#install python3.7
+RUN apt-get update && apt-get install -y software-properties-common && \
+    apt-add-repository -r ppa:armagetronad-dev/ppa && \
+    apt-get update && apt-get install -y python3.7 python3-pip \
+    python3-distutils python3-setuptools && \
+    python3.7 -m pip install pip --upgrade pip && \
+    echo "alias python=python3.7" >> ~/.bashrc && \
+    export PATH=${PATH}:/usr/bin/python3.7 && \
+    /bin/bash -c "source ~/.bashrc" && \
+    update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1 && \
+    update-alternatives --set python /usr/bin/python3.7
 
 # install spark
-RUN wget --no-verbose https://downloads.apache.org/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz
-RUN tar -xzvf spark-3.1.1-bin-hadoop3.2.tgz
-RUN mv spark-3.1.1-bin-hadoop3.2 /opt/spark
-RUN rm -rf spark-3.1.1-bin-hadoop3.2.tgz
+RUN wget --no-verbose https://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz && \
+    tar -xzvf spark-3.1.1-bin-hadoop3.2.tgz && \
+    mv spark-3.1.1-bin-hadoop3.2 /opt/spark && \
+    rm -rf spark-3.1.1-bin-hadoop3.2.tgz
 
 ENV SPARK_HOME=/opt/spark
 ENV PATH=$PATH:$SPARK_HOME/bin
 ENV PATH=$PATH:$SPARK_HOME/sbin
-ENV PYTHONPATH=$SPARK_HOME/python3:$SPARK_HOME/python3/lib/py4j-0.10.7-src.zip:$PYTHONPATH
-RUN mkdir -p /opt/spark/history
-COPY container/spark-defaults.conf /opt/spark/conf/spark-defaults.conf
+ENV PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.9-src.zip:$PYTHONPATH
 
 COPY container/requirements.txt requirements.txt
-RUN pip install --no-cache-dir -r requirements.txt
+RUN pip install --upgrade pip && \
+    pip install --no-cache-dir -r requirements.txt && \
+    rm -rf requirements.txt
 
-RUN mkdir -p /opt/project
-ADD container/common.sh container/spark-master container/spark-worker /
+RUN mkdir -p /opt/work-dir
+COPY ./src /opt/work-dir
+
+COPY container/entrypoint.sh /opt/
+COPY container/decom.sh /opt/
+
+RUN chmod g+w /opt/work-dir
+RUN chmod a+x /opt/decom.sh
+
+WORKDIR /opt/work-dir
+ENTRYPOINT [ "/opt/entrypoint.sh" ]
